version: 2

project_name: freighter
before:
  hooks:
    - go mod tidy
    - go mod download
    - go fmt ./...
    - go vet ./...
    - go test ./... -cover -race -covermode=atomic -coverprofile=coverage.out

release:
  prerelease: auto
  make_latest: false

env:
  - vpkg=freighter.dev/go/freighter/internal/version
  - cosign_version=v2.2.3+carbide.3

builds:
  - dir: ./cmd/freighter/.
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X {{ .Env.vpkg }}.gitVersion={{ .Version }} -X {{ .Env.vpkg }}.gitCommit={{ .ShortCommit }} -X {{ .Env.vpkg }}.gitTreeState={{if .IsGitDirty}}dirty{{else}}clean{{end}} -X {{ .Env.vpkg }}.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=boringcrypto

universal_binaries:
  - replace: false

changelog:
  disable: false
  use: git

brews:
  - name: freighter
    repository:
      owner: freighter-dev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    description: "Freighter CLI"

dockers:
  - id: freighter-amd64
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--target=release"
    image_templates:
      - "docker.io/freighter/freighter-amd64:{{ .Version }}"
      - "ghcr.io/freighter-dev/freighter-amd64:{{ .Version }}"
  - id: freighter-arm64
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--target=release"
    image_templates:
      - "docker.io/freighter/freighter-arm64:{{ .Version }}"
      - "ghcr.io/freighter-dev/freighter-arm64:{{ .Version }}"
  - id: freighter-debug-amd64
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--target=debug"
    image_templates:
      - "docker.io/hauler/hauler-debug-amd64:{{ .Version }}"
      - "ghcr.io/hauler-dev/hauler-debug-amd64:{{ .Version }}"
  - id: hauler-debug-arm64
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--target=debug"
    image_templates:
      - "docker.io/hauler/hauler-debug-arm64:{{ .Version }}"
      - "ghcr.io/hauler-dev/hauler-debug-arm64:{{ .Version }}"

docker_manifests:
  - id: hauler-docker
    use: docker
    name_template: "docker.io/hauler/hauler:{{ .Version }}"
    image_templates:
      - "docker.io/hauler/hauler-amd64:{{ .Version }}"
      - "docker.io/hauler/hauler-arm64:{{ .Version }}"
  - id: hauler-ghcr
    use: docker
    name_template: "ghcr.io/hauler-dev/hauler:{{ .Version }}"
    image_templates:
      - "ghcr.io/hauler-dev/hauler-amd64:{{ .Version }}"
      - "ghcr.io/hauler-dev/hauler-arm64:{{ .Version }}"
  - id: hauler-debug-docker
    use: docker
    name_template: "docker.io/hauler/hauler-debug:{{ .Version }}"
    image_templates:
      - "docker.io/hauler/hauler-debug-amd64:{{ .Version }}"
      - "docker.io/hauler/hauler-debug-arm64:{{ .Version }}"
  - id: hauler-debug-ghcr
    use: docker
    name_template: "ghcr.io/hauler-dev/hauler-debug:{{ .Version }}"
    image_templates:
      - "ghcr.io/hauler-dev/hauler-debug-amd64:{{ .Version }}"
      - "ghcr.io/hauler-dev/hauler-debug-arm64:{{ .Version }}"
